# Generated by Django 4.2.7 on 2023-12-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=6, verbose_name='price'),
        ),
    ]
